@HostAddress = http://localhost:5200

POST {{HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "dima@gmail.com",
  "password": "qwerty123"
}

###
POST {{HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "dima@gmail.com",
  "password": "qwerty123"
}