@HostAddress = http://localhost:5200
@Token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZDBmMTNkNy03M2VjLTRhY2QtOTVlZi0xZDk5NGFiY2VjMmEiLCJlbWFpbCI6ImRpbWFAZ21haWwuY29tIiwiZXhwIjoxNzM0MTM2NjA4LCJpc3MiOiJGdW5kUmFpc2luZyIsImF1ZCI6IkZ1bmRSYWlzaW5nIn0.uIAZY8-Z_X4NzdWHvex05zrjB370saKSncEhGGzjK5Y
@Id = daaf0331-cfa9-4347-8a21-845b24e471a3
@Card = 4000000000003055
@CardInvalid = 4000000000000002
@CardExpiryDate = 10/26
@CardCvv = 344

POST {{HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "dima@gmail.com",
  "password": "qwerty123"
}

###
POST {{HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "dima@gmail.com",
  "password": "qwerty123"
}

###
GET {{HostAddress}}/fundraisers
Content-Type: application/json
Authorization: {{Token}}

###
GET {{HostAddress}}/fundraisers/{{Id}}
Content-Type: application/json

###
POST {{HostAddress}}/fundraisers
Content-Type: application/json
Accept: application/json
Authorization: {{Token}}

{
  "title": "Some title",
  "description": "Some description",
  "goal": "10000000"
}

###
PUT {{HostAddress}}/fundraisers/{{Id}}
Content-Type: application/json
Accept: application/json
Authorization: {{Token}}

{
  "title": "Some title",
  "description": "Some description",
  "goal": "1000"
}

###
POST {{HostAddress}}/fundraisers/{{Id}}/donate
Content-Type: application/json
Accept: application/json
Authorization: {{Token}}

{
  "description": "some description",
  "amount": "1",
  "card": "{{Card}}",
  "cardExpiryDate": "{{CardExpiryDate}}",
  "cardCvv": "{{CardCvv}}"
}

###
DELETE {{HostAddress}}/fundraisers/{{Id}}
Content-Type: application/json
Authorization: {{Token}}